feat: add header component
coders-camp-2021-best-team/web-development-basics pull request #22
Opened 2021-12-08 21:02 UTC by T0ffik

2021-12-08 21:49 UTC, Veryyapeee submitted a review, later dismissed
Menu is not responsive at all

2021-12-10 13:24 UTC, T0ffik commented
> Menu is not responsive at all
Done. I think.

2021-12-10 13:40 UTC, T0ffik commented
> Menu is not responsive at all

2021-12-10 13:43 UTC, T0ffik commented
> Menu is not responsive at all 

Done. I think.

2021-12-10 13:52 UTC, T0ffik reviewed
Done. I think.

2021-12-10 14:30 UTC, Veryyapeee commented
I think that we need some horizontal padding in this menu

2021-12-10 14:32 UTC, Veryyapeee commented on src/components/header/Header.js
> +    <div id="header">
This should be a `<header/>` tag

2021-12-10 14:32 UTC, Veryyapeee commented on src/components/header/_header.scss
> +#header{
Generally to whole styling here
Don't use ID's for styling, use class instead

2021-12-10 14:33 UTC, Veryyapeee commented on src/components/header/_header.scss
> +    padding-left: 10px;
you can replace it with
`padding: 0 10px;`

2021-12-10 14:33 UTC, Veryyapeee commented on src/components/header/_header.scss
> +          background-color: rgba(0, 0, 0, 0);
even if it's just a black color, this should be in variables, add it please

2021-12-10 14:34 UTC, Veryyapeee commented on src/components/header/_header.scss
> +        padding-left: 25px;
`padding: 0 25px;`

2021-12-10 14:34 UTC, Veryyapeee commented on src/components/header/_header.scss
> +      background-color: #B9B9B7;
This should be in variables.scss

2021-12-10 14:36 UTC, Veryyapeee submitted a review, later dismissed
check the comments

2021-12-10 22:34 UTC, Veryyapeee requested changes, later dismissed

2021-12-10 22:34 UTC, Veryyapeee commented on src/components/header/Header.js
> +          <button id="icon" class="icon"><img src="/static/img/menuIcon.png" alt="menu"></button>
Alt should be meaningfull, it's for accesibility reasons, so it should be something like, toggleMenuIcon
Minor

2021-12-10 22:34 UTC, Veryyapeee commented on src/components/header/Header.js
> +const template= (close, open) =>`
You are not using this close and open functions,

Convert this back to be an const instead od function, just plain html :p

2021-12-10 22:34 UTC, Veryyapeee commented on src/components/header/Header.js
> +          <li>Movie</li>
Add TODO that in the future we need to connect these elements with redirect function

2021-12-11 12:19 UTC, Veryyapeee approved these changes

2021-12-11 12:22 UTC, Mariusz-web approved these changes

2021-12-11 12:28 UTC, merged